Connected cart with redux
BuildForSDGCohort2/Team-254-zaoBora-frontend pull request #30
Opened 2020-09-22 11:59 UTC by zanderthuo

Register route.
 Login route.
 Products route.
 Reviews route.
 User orders.
 Vendor profile route.
 Vendor orders route.
 Vendor products route.
 Cart route.

2020-09-22 12:24 UTC, Dave-mash commented on src/actions/types.js
> +export const CLEAR_ITEM_FROM_CART = 'CLEAR_ITEM_FROM_CART';
move these types to constants file in utils folder

2020-09-22 12:25 UTC, Dave-mash commented on src/index.js
> +RenderApp();
Don't Capitalize this function name

2020-09-22 12:28 UTC, Dave-mash requested changes
Requested changes

2020-09-22 19:51 UTC, Dave-mash approved these changes

2020-09-23 08:10 UTC, Jordan-type approved these changes

2020-09-23 08:12 UTC, merged